variable region {}
variable account_id {}
variable log_group {}
variable default_tags {}
variable module_bucket {}
variable module_staging_bucket {}
variable elastic_domain_arn {}
variable elastic_endpoint {}
variable elastic_index {}